# Generated by Django 5.2.7 on 2025-12-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_practica_imagen_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('book_title', models.CharField(max_length=255)),
                ('borrower_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('document_number', models.CharField(max_length=100)),
                ('days', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
