# Generated by Django 5.2.7 on 2025-12-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_prestamo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('editorial', models.CharField(blank=True, max_length=255, null=True)),
                ('año', models.IntegerField(blank=True, null=True)),
                ('categoria', models.CharField(default='Libros', max_length=200)),
                ('imagen_url', models.URLField(blank=True, max_length=500, null=True)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
